print("Welcome to my Mad Libs story!\nThere is only one rule... One word per input!")
type_summer = input("What type of summer day is it?")
friend = input("Who were you with?")
where_camping = input("Where did you go camping?")
fav_clothing = input("What is your favorite piece of clothing?")
describe_clothing = input("Describe your clothing in one word")
van_description = input("Describe the type of van you were in for the trip")
song_name = input("What is the name of the song you were listening to in the van?")
what_food = input("What food was being cooked that you could smell?")
how_smell = input("How did the food smell?")
walk_room = input("How did you go to the room? (Did you walk or run)")
room_mate = input("Who was your roommate?")
how_trip = input("How was your camping trip?")
print("")
print("")
print("It was a " + type_summer + " summer day. " + friend + " and I were\nexcited to go camping at " + where_camping)
print("It was my first time going there. I packed my favorite " + fav_clothing + ". It is " + describe_clothing + ".")
print("Perfect for camping! On the road we went in our " + van_description + " van!\nWe were listening to " + song_name + " all the way down")
print("The drive was about 5 hours but it was so worth it.\nWhen we got there we unpacked the van. I could smell " + what_food)
print("being cooked. It smelled " + how_smell + " .")
print("I " + walk_room + " to the room I was staying in with my " + room_mate)
print("My camping trip was " + how_trip)